### ISSUE TITLE
CKAN Support

### ISSUE THREAD

**Issue by enmaku** [UbioWeldingLtd/UbioWeldContinued#38]
Not an "issue" per se, but it would make life a lot easier for a lot of us if this project could be included in CKAN for easy installation/update/removal.

CKAN has a pretty comprehensive guide on adding mods to their repository [on their github wiki](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN)

**Comment by dertroglodyt** [comment]
Where can I vote this up? ;-)

**Comment by Darael** [comment]
I have a draft `.netkan` file which could be used (in a fire-and-forget manner, since it refers to the `.version` file in this repo to handle KSP version bumps and so on) to close this issue, but I don't want to submit it for inclusion without checking first.  So.  Is this wishlist or wontfix?

(side note: CKAN's automatic github-release detection ignores things marked as "pre-release", so as things stand it could only pick up the last 1.0.5-compatible version of UW.  If the work to adapt the mod for 1.1 seems stable, and you'd like me to submit to the CKAN, please consider doing a "proper" GH release)

**Comment by Alewx** [comment]
You can make a pullrequest for the file if you have one.

**Comment by Darael** [comment]
I'll do that - but owing to the way CKAN works it'll be against their NetKAN repository, rather than this one, in order to be useful.

**Comment by Darael** [comment]
Just to be absolutely clear, the latest version still won't show in CKAN because they don't index releases tagged as "pre-release".

Once there's a "proper" release on GH, though, I'd say you're good to close this issue.  Shouldn't come up again, unless the repository changes or the dependencies need tweaking or something.

**Comment by Alewx** [comment]
I'm still working on a proper release.
Hope to get it done within the next two weeks.

**Comment by Darael** [comment]
Shiny.  Just making sure you weren't expecting the prerelease to show up in CKAN, is all.

**Comment by Alewx** [comment]
Oh a Firefly fan :P
Ok that is good to know, does CKAN require any other preps?

**Comment by Darael** [comment]
While, yes, I like Firefly, I was using "shiny" before ever I saw it.  Honest. :P

And no, CKAN (specifically, @netkan-bot) will pick up "proper" GitHub releases automatically within a few hours of their happening.  That will only stop if the file in KSP-CKAN/NetKAN is edited to point elsewhere or deleted.  If, however, UbioWeld acquires any _dependencies_ on other mods, CKAN won't know about it until said file is tweaked to include them, and as such may allow broken installs.

**Comment by Alewx** [comment]
Is listed in CKAN
